# Generated by Django 3.2.12 on 2023-11-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username1', models.CharField(max_length=100)),
                ('username2', models.CharField(max_length=100)),
                ('winner', models.CharField(max_length=100)),
            ],
        ),
    ]
