# Generated by Django 3.2.12 on 2024-01-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponggame',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
