# Generated by Django 3.2.12 on 2023-11-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_games', models.IntegerField()),
                ('number_of_wins', models.IntegerField()),
            ],
        ),
    ]
