# Generated by Django 3.2.12 on 2023-12-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBack', '0002_alter_tournament_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='tournaments', to='djangoBack.Player'),
        ),
    ]
