# Generated by Django 3.2.12 on 2024-01-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBack', '0002_ponggame_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
