# Generated by Django 3.2.12 on 2024-01-19 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBack', '0002_oauthuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OAuthUser',
        ),
    ]
