# Generated by Django 3.2.12 on 2024-01-09 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBack', '0003_alter_match_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='player_one',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player_one', to='djangoBack.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player_two', to='djangoBack.player'),
        ),
    ]
