# Generated by Django 3.2.12 on 2023-11-09 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBack', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
    ]
