# Generated by Django 3.2.12 on 2023-11-20 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBack', '0003_auto_20231119_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='PongGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_one_socket_id', models.CharField(blank=True, max_length=255, null=True)),
                ('player_two_socket_id', models.CharField(blank=True, max_length=255, null=True)),
                ('score_player_one', models.IntegerField(default=0)),
                ('score_player_two', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('playing', 'Playing'), ('complete', 'Complete')], default='waiting', max_length=10)),
                ('isPaused', models.BooleanField(default=False)),
                ('player_one', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_one_game', to=settings.AUTH_USER_MODEL)),
                ('player_two', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_two_game', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
