# Generated by Django 3.2.12 on 2023-12-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBack', '0004_auto_20231120_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponggame',
            name='player_one_channel_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ponggame',
            name='player_two_channel_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
