# Generated by Django 3.2.12 on 2023-11-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBack', '0004_remove_user_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='username1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='username2',
        ),
        migrations.AddField(
            model_name='game',
            name='isPaused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='player1Score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='player1Username',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='player2Score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='player2Username',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('in-progress', 'In Progress'), ('completed', 'Completed')], default='waiting', max_length=12),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(default='', max_length=100),
        ),
    ]
