# Generated by Django 3.2.12 on 2024-01-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBack', '0004_tournament_participants_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nbre_games',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='won_game',
            field=models.IntegerField(default=0),
        ),
    ]
