# Generated by Django 3.2.12 on 2023-12-10 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBack', '0005_auto_20231209_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ponggame',
            name='player_one_channel_name',
        ),
        migrations.RemoveField(
            model_name='ponggame',
            name='player_two_channel_name',
        ),
    ]
