# Generated by Django 3.2.12 on 2023-11-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBack', '0005_user_is_two_factor_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_factor_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_code_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
