# Generated by Django 3.2.12 on 2023-11-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBack', '0007_auto_20231111_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_method',
            field=models.CharField(choices=[('email', 'Email'), ('qr', 'QR')], default='email', max_length=10),
        ),
    ]
