# Generated by Django 3.2.12 on 2023-11-12 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBack', '0005_auto_20231111_1418'),
        ('djangoBack', '0007_auto_20231111_1814'),
    ]

    operations = [
    ]
