# Generated by Django 3.2.12 on 2023-11-12 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBack', '0008_auto_20231112_1142'),
        ('djangoBack', '0008_merge_0005_auto_20231111_1418_0007_auto_20231111_1814'),
    ]

    operations = [
    ]
