# Generated by Django 3.2.12 on 2023-11-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBack', '0011_auto_20231114_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('en ligne', 'En ligne'), ('hors ligne', 'Hors ligne'), ('en jeu', 'En jeu')], default='hors ligne', max_length=10),
        ),
    ]
