# Generated by Django 3.2.12 on 2023-11-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBack', '0012_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='two_factor_method',
            field=models.CharField(choices=[('email', 'Email'), ('qr', 'QR'), ('none', 'NONE')], default='none', max_length=10),
        ),
    ]
