# Generated by Django 3.2.12 on 2023-11-17 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBack', '0015_user_websocket_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='websocket_id',
        ),
    ]
