# Generated by Django 3.2.12 on 2023-11-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBack', '0017_user_socket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='game_socket_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
